### ISSUE TITLE
Extending documentation?

### ISSUE THREAD

**Issue by tryshchenko** [braposo/graphql-css#1]
Hi,

Don't understand me wrong; I really appreciate your effort guys. 
However, at the moment I have no idea what problem this library solves. I can't understand why I possibly may need it. I still with "WTF is going on here" question in my mind.

Some kind of cookbook or explanation on some example would be a very cool point to answer this question. I'm pretty sure that not only I got confused.

What are PROS/CONS?

**Comment by davidgomes** [comment]
Hi tryshchenko,

Thank you for your valuable feedback. As we hope you might understand, our enterprise library is still in its early phases and so we're still working on the best way to explain the community its purposes and its value.

There are so many ways in which GraphQL can be explored (and over engineered) that we are honestly still not sure of where it can actually be a useful tool. It started on the server, and now it's on the client and in the future will it be used for everything (including CSS)?

We'll be keeping this issue open and updating it as we make more progress on it.

**Comment by ubergarm** [comment]
This is adult swim style humor. Millenials and younger eat this stuff up. Its [Dadaism](https://en.wikipedia.org/wiki/Dada) reaction to the cambrian explosion occuring in web development. Or I'm just too old to get it. Either way, going back to my Linux console now. Cheers.

**Comment by tryshchenko** [comment]
Guys, I was thinking and decided that we might find the use case together.
I create a library of advanced CSS color and background color manipulation.
https://github.com/tryshchenko/farvekonfigurator

I believe it should dramatically increase performance, what do you think?
I think we need to consider integration, don't we?

**Comment by braposo** [comment]
Hi @tryshchenko, thanks for your kind offer.

At this moment we're focused on delivering the best experience possible to our users and partners so I'm afraid any 3rd party integration will need to be put oh hold for now. We wish you all the success for your library!

As a side note, I'm going to close this issue because we've been preparing a short video course to be released soon so it will make everything much easier to understand. Thanks again for opening it in the first place!
